aws-samples/aws-dynamodb-examples

- DynamoDB-SDK-Examples/java/README.md
- DynamoDB-SDK-Examples/java/WorkingWithItems/BatchGetItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/BatchWriteItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/DeleteItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/GetItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/PutItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/PutItemConditional.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/TransactGetItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/TransactWriteItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/UpdateItem.java
- DynamoDB-SDK-Examples/java/WorkingWithItems/UpdateItemConditional.java
Added Java V2 DynamoDB Enhanced Client WorkingWithItems examples.
> Adding Java V2 Enahanced Client Examples

- DynamoDB-SDK-Examples/java/README.md
- DynamoDB-SDK-Examples/java/WorkingWithQueries/QueryConsistentRead.java
- DynamoDB-SDK-Examples/java/WorkingWithQueries/QueryWithFilterExpression.java
- DynamoDB-SDK-Examples/java/WorkingWithQueries/QueryWithProjectionExpression.java
- DynamoDB-SDK-Examples/java/WorkingWithQueries/QueryWithSortKey.java
Added Working with Queries for Java SDK-V2 DynamoDB Enhanced Client
> Java SDK-V2 EnhancedClient WorkingWithQueries

- DynamoDB-SDK-Examples/python/README.md
- DynamoDB-SDK-Examples/python/WorkingWithScans/scan_filter_expression.py
- DynamoDB-SDK-Examples/python/WorkingWithScans/scan_paginate.py
- DynamoDB-SDK-Examples/python/WorkingWithScans/scan_parallel.py
- DynamoDB-SDK-Examples/python/WorkingWithScans/scan_projection_expression.py
- DynamoDB-SDK-Examples/python/WorkingWithScans/scan_simple.py
- DynamoDB-SDK-Examples/python/WorkingWithScans/scan_with_paginator.py
Added example Scan operations for Python
> Python Working With Scans Examples

- DynamoDB-SDK-Examples/golang/README.md
- DynamoDB-SDK-Examples/golang/WorkingWithItems/batchGetItem.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/batchWriteItem.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/deleteItem.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/deleteItemConditional.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/getItem.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/putItem.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/putItemConditional.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/updateItem.go
- DynamoDB-SDK-Examples/golang/WorkingWithItems/updateItemConditional.go
Added item level operations for Go
> Working With Items Go

- Cloudformation/GlobalTables/GlobalTable_OnDemand.json
- Cloudformation/GlobalTables/GlobalTable_OnDemand.yml
- Cloudformation/GlobalTables/GlobalTable_Provisioned.json
- Cloudformation/GlobalTables/GlobalTable_Provisioned.yml
- Cloudformation/Process_new_items_dynamodb_steams.yml
Add Cloudformation templates for creating Global Tables in YAML and JSON form.
Templates for both On-demand and Provisioned Mode
> Added CFN templates for Global Tables

- DynamoDB-SDK-Examples/rust/README.md
- DynamoDB-SDK-Examples/rust/working_with_queries/Cargo.toml
- DynamoDB-SDK-Examples/rust/working_with_queries/README.md
- DynamoDB-SDK-Examples/rust/working_with_queries/src/prepare-query-data/main.rs
- DynamoDB-SDK-Examples/rust/working_with_queries/src/query-consistent-read/main.rs
- DynamoDB-SDK-Examples/rust/working_with_queries/src/query-consumed-capacity/main.rs
- DynamoDB-SDK-Examples/rust/working_with_queries/src/query-projection/main.rs
- DynamoDB-SDK-Examples/rust/working_with_queries/src/query-scan-filter/main.rs
- DynamoDB-SDK-Examples/rust/working_with_scans/Cargo.toml
- DynamoDB-SDK-Examples/rust/working_with_scans/README.md
- DynamoDB-SDK-Examples/rust/working_with_scans/src/scan-in-parallel/main.rs
- DynamoDB-SDK-Examples/rust/working_with_scans/src/scan-with-pagination/main.rs
Added new examples:
1. Query with consistent read
2. Query with projection
3. Query with scan filter
4. Query that returns consumed capacity
5. Scan in parallel
6. Scan with pagination
> Add some Rust example code for DynamoDB Query & Scan API

- cloudformation/global_tables/GlobalTable_OnDemand.yml
Cloudformation template for on-demand GT in YAML was actually in JSON. Made the changes to correct this.
> Refactoring Global Table On Demand YAML

- DynamoDB-SDK-Examples/rust/working_with_items/Cargo.toml
- DynamoDB-SDK-Examples/rust/working_with_items/src/batch-get/main.rs
- DynamoDB-SDK-Examples/rust/working_with_items/src/batch-write/main.rs
> Add Rust SDK example for batch get & batch write API

- DynamoDB-SDK-Examples/rust/working_with_items/Cargo.toml
- DynamoDB-SDK-Examples/rust/working_with_items/src/put-item/main.rs
- DynamoDB-SDK-Examples/rust/working_with_items/src/transact-get/main.rs
- DynamoDB-SDK-Examples/rust/working_with_items/src/transact-put/main.rs
- DynamoDB-SDK-Examples/rust/working_with_streams/Cargo.toml
- DynamoDB-SDK-Examples/rust/working_with_streams/src/disable-update-streams/main.rs
- DynamoDB-SDK-Examples/rust/working_with_streams/src/enable-update-streams/main.rs
> Add Rust example for Transact Put and Transact Get

- DynamoDB-SDK-Examples/rust/working_with_indexes/Cargo.toml
- DynamoDB-SDK-Examples/rust/working_with_indexes/README.md
- DynamoDB-SDK-Examples/rust/working_with_indexes/src/create-index/main.rs
- DynamoDB-SDK-Examples/rust/working_with_indexes/src/delete-index/main.rs
- DynamoDB-SDK-Examples/rust/working_with_indexes/src/query-index/main.rs
> Add Rust example for GlobalSecondaryIndex

- cloudformation/global_tables/GlobalTable_OnDemand.yml
Spotted duplicate code in one file. Refactored
> Removing duplicate code from OnDemand YAML

- DynamoDB-SDK-Examples/README.md
- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/batch-execute-statement.js
1. Added batchExecuteStatement with PartiQL NodeJS example.
2. Added reference to examples on ReadMe.
3. Rectified some broken links on ReadMe.
> Added PartiQL NodeJS example

- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/batch-execute-statement.js
- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/sanitization-for-sql-injection.js
- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/sql-injection.js
N/A
In PartiQL examples for NodeJS have added SQL injection sample and also a way to sanitize the inputs.
> Added SQL injection sample

- DynamoDB-SDK-Examples/README.md
- DynamoDB-SDK-Examples/python/README.md
- DynamoDB-SDK-Examples/python/WorkingWithPartiQL/simple-select-statement.py
N/A
Added Python example for boto3 PartiQL execute_statement method to demonstrate a simple-select-statement. Added README links.
> Add Python PartiQL Select Statement example

- DynamoDB-SDK-Examples/README.md
- DynamoDB-SDK-Examples/python/README.md
- DynamoDB-SDK-Examples/python/WorkingWithPartiQL/batch-execute-statement.py
- DynamoDB-SDK-Examples/python/WorkingWithPartiQL/execute-statement.py
- DynamoDB-SDK-Examples/python/WorkingWithPartiQL/execute-transaction.py
N/A
Added examples for Python boto3 PartiQL ExecuteStatement, ExecuteTransaction, BatchExecuteStatement.
> Update Python PartiQL examples

- DynamoDB-SDK-Examples/node.js/WorkingWithIndexes/create-index.js
Added create-index sample for NodeJS
> Added create-index sample for NodeJS

- DynamoDB-SDK-Examples/node.js/WorkingWithStreams/read-stream.js
*Issue #, if available:* - 
*Description of changes:* change node stream reader sample to v3 sdk
> change node stream reader sample to v3 sdk

- DynamoDB-SDK-Examples/python/WorkingWithCustomBackoffRetry/exponential_backoff_retry_get_item.py
Issue #82 
*Python example added for custom exponential back off and retry logic*
> Custom exponential back off and retry for python #82

- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/paginated-all-data.js
https://github.com/aws-samples/aws-dynamodb-examples/issues/73 Added sample.
Added NodeJS sample for PartiQL with pagination for all data (scan operation) in DynamoDB.
> Added PartiQL with Pagination sample NodeJS

- DynamoDB-SDK-Examples/python/WorkingWithPartiQL/paginated-select-statement.py
*Issue #:*
#75
Python example for pagination with partiql. 
> Python Example: Pagination of data returned by partiql execute statement. 

- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/paginated-all-data.js
https://github.com/aws-samples/aws-dynamodb-examples/issues/73 fixed await issue and added inside a async block.
> Fixed the await issue

- SchemaDesign/WriteSharding/README.md
- SchemaDesign/WriteSharding/python/WriteShardingExample.py
#70 
Created a new folder for SchemaDesign and subfolder for WriteSharding. Can modify this if needed. 
Created Python sample for randomized and calculated suffixes for write sharding.
> Python Write sharding example

- DynamoDB-SDK-Examples/node.js/WorkingWithPartiQL/paginated-all-data.js
https://github.com/aws-samples/aws-dynamodb-examples/issues/73#issuecomment-959798268 Added the missing semi colon.
> Added missing semi-colon

- DynamoDB-SDK-Examples/node.js/WorkingWithCustomBackoffRetry/exponential_backoff_retry_get_item.js
*Issue #67 *
Aws-example nodejs code for custom retry and exponential back off
> Nodejs example for customback off and exponential retry for DynamoDB 

- DynamoDB-SDK-Examples/java/README.md
- DynamoDB-SDK-Examples/java/WorkingWithTables/CreateTableOnDemand.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/CreateTableProvisioned.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/DeleteTable.java
Making a start with adding Java examples to the set of WorkingWithTables examples
> Java SDK-V2 EnhancedClient WorkingWithTables

- DynamoDB-SDK-Examples/node.js/WorkingWithCustomBackoffRetry/exponential_backoff_retry_get_item.js
*Issue #, if available:* N/A
The condition variable was being set to `False` instead of `false`. This PR fixes that
> Updates condition value to a proper boolean

- DynamoDB-SDK-Examples/java/README.md
- DynamoDB-SDK-Examples/java/WorkingWithTables/AddProvisionedCapacity.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/DescribeLimits.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/DescribeTable.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/ListTables.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/TableChangeToOnDemand.java
- DynamoDB-SDK-Examples/java/WorkingWithTables/TableChangeToOnProvisioned.java
Adding more Java based examples in the WorkingWithTables category
> Java SDK-V2 adding multiple WorkingWithTables examples

- DynamoDB-SDK-Examples/node.js/WorkingWithTables/export_table_s3.js
- DynamoDB-SDK-Examples/python/WorkingWithTables/export_table_s3.py
*Issue #92 *
Add code example for export dyanmodb table to s3 bucket in nodejs and python. 
> Nodejs | Python code example for Export Table to S3

- DynamoDB-SDK-Examples/node.js/WorkingWithCustomBackoffRetry/exponential_backoff_retry_get_item.js
Adding declaration for backoffTime as per customer feedback
> Adding declaration for backoffTime

- README.md
> Langchain example

- scripts/README.md
> remove update me flag from README.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/issue-template.md
> Update issue templates

- scripts/docker/README.md
*Issue #, if available:* 136
*Description of changes:* Uploaded README.md file.
Hopefully the whole thing comes through this time 😆 
> Secondreadme

- examples/NERDS/basic-template/README.md
*Issue #, if available:* N/A
*Description of changes:* Adding YouTube video to the NERDS/basic-stack/README.md
> doc: Adding the basic-stack video to the README.md

- examples/SDK/kotlin/Operations.md
- examples/SDK/kotlin/README.md
See https://github.com/aws-samples/aws-dynamodb-examples/issues/149
*Issue #, if available:* #149
> feat: Adding readme file and directory structure for Kotlin examples

- examples/SDK/python/data_plane/WorkingWithItems/put_item_conditional.py
- examples/SDK/python/data_plane/WorkingWithItems/update_item_conditional.py
*Issue #145, if available:*
Added two files for examples on how to use conditional option for PutItem and UpdateItem APIs for Python.
> Python conditional samples

- schema_design/SchemaExamples/ConnectedVehicles/README.md
Added PR to SchemaExamples/ConnectedVehicles
> Added PR to SchemaExamples/ConnectedVehicles

- scripts/nosqlworkbenchscript/README.md
Issue #137 
Enhancements to README.md, including execution samples and additional information to the reader on what to expect from the script.
> Issue 137 scripts   no sql workbench enhance README.md

- .github/workflows/main.yaml
> Adding sync action for relational-migration workshop

- schema_design/SchemaExamples/SessionManagement/README.md
Issue #132 session management needs readme
Created new README.md for Session Management schema. Based on documentation given in link by @tebanieo. 
> Issue 132 session management needs readme

- workshops/relational-migration/load/jobs/Ledger.py
This small PR fixes the syntax error in the Ledger job.
> fix: correct the Ledger job

- examples/SDK/node.js/sdk_v3/data_plane/WorkingWithItems/update-item-list.js
*Issue #, if available:* Issue #98
Example of UpdateItem command for NodeJS with list manipulation
> NodeJS Examples: UpdateCommand with list manipulation.

- workshops/modernizr/frontend/src/App.tsx
- workshops/modernizr/frontend/src/contexts/AuthContext.tsx
- workshops/modernizr/frontend/src/contexts/CartContext.tsx
- workshops/modernizr/frontend/src/pages/CategoriesPage.tsx
- workshops/modernizr/frontend/src/pages/CheckoutPage.tsx
- workshops/modernizr/frontend/src/pages/CreateProductPage.tsx
- workshops/modernizr/frontend/src/pages/EditProductPage.tsx
- workshops/modernizr/frontend/src/pages/OrderDetailPage.tsx
- workshops/modernizr/frontend/src/pages/OrderHistoryPage.tsx
- workshops/modernizr/frontend/src/pages/ProductDetailPage.tsx
- workshops/modernizr/frontend/src/pages/ProductsPage.tsx
- workshops/modernizr/frontend/src/pages/SellerDashboardPage.tsx
- workshops/modernizr/frontend/src/pages/SellerProductsPage.tsx
- workshops/modernizr/frontend/src/pages/UpgradeSellerPage.tsx
- workshops/modernizr/frontend/src/services/api.ts
*Issue #, if available:* 
*Description of changes:* Removed the /api from the apis, let it retrieve from the global config. 
> bugfix: Removing hardcoded /api from front end pages. 

- workshops/modernizr/docker/docker-compose.yml
- workshops/modernizr/prompts/00-mysql-dynamodb-migration-orchestrator/design.md
- workshops/modernizr/prompts/00-mysql-dynamodb-migration-orchestrator/tasks.md
- workshops/modernizr/prompts/03-dual-database-abstraction/design.md
- workshops/modernizr/prompts/03-dual-database-abstraction/requirements.md
- workshops/modernizr/prompts/03-dual-database-abstraction/tasks.md
- workshops/modernizr/prompts/04-dynamodb-implementation/design.md
- workshops/modernizr/prompts/04-dynamodb-implementation/requirements.md
- workshops/modernizr/prompts/04-dynamodb-implementation/tasks.md
*Description of changes:* Continued adding the prompts for stages 3 and 4, included a docker compose instructions that will start a dynamodb local with shared memory.
> feat: including docker compose for DDB local and stages 3 and 4

- workshops/modernizr/prompts/02-a-dynamodb-data-modeling/design.md
- workshops/modernizr/prompts/02-a-dynamodb-data-modeling/requirements.md
- workshops/modernizr/prompts/02-a-dynamodb-data-modeling/tasks.md
- workshops/modernizr/prompts/04-dynamodb-implementation/design.md
- workshops/modernizr/prompts/04-dynamodb-implementation/tasks.md
- workshops/modernizr/prompts/05-feature-flags-system/design.md
- workshops/modernizr/prompts/05-feature-flags-system/requirements.md
- workshops/modernizr/prompts/05-feature-flags-system/tasks.md
*Description of changes:*  Added additional prompts for MCP server interactions, Enhanced unit and integration testing requirements and prompts for feature flags development.
> Feat: Adding feature flag system, enabling mcp chat

- workshops/modernizr/prompts/03-dual-database-abstraction/tasks.md
- workshops/modernizr/prompts/04-dynamodb-implementation/tasks.md
- workshops/modernizr/prompts/05-feature-flags-system/tasks.md
*Description of changes:* Added updated prompts for stage 05 in modernizr
> Modernizr: Feature Flag System Modernizr backend and frontend - Stage 05

- workshops/modernizer/prompts/07-data-migration-execution/tasks.md
*Description of changes:* Added additional guardrails for prompt execution on stage 07 to ensure smooth execution and less back and forth conversation. 
> Prompt clarification on modernizer Stage 07
